export const KOTA_INDONESIA = [
  "Ambon",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Banjar",
  "Banjarbaru",
  "Banjarmasin",
  "Batam",
  "Batu",
  "Baubau",
  "Bekasi",
  "Bengkulu",
  "Bima",
  "Binjai",
  "Bitung",
  "Blitar",
  "Bogor",
  "Bontang",
  "Bukittinggi",
  "Cilegon",
  "Cimahi",
  "Cirebon",
  "Denpasar",
  "Depok",
  "Dumai",
  "Gorontalo",
  "Gunungsitoli",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Jambi",
  "Jayapura",
  "Kediri",
  "Kendari",
  "Kotamobagu",
  "Kupang",
  "Langsa",
  "Lhokseumawe",
  "Lubuklinggau",
  "Madiun",
  "Magelang",
  "Makassar",
  "Malang",
  "Manado",
  "Mataram",
  "Medan",
  "Metro",
  "Mojokerto",
  "Padang",
  "Padangsidimpuan",
  "Pagar Alam",
  "Palangka Raya",
  "Palembang",
  "Palopo",
  "Palu",
  "Pangkalpinang",
  "Parepare",
  "Pariaman",
  "Pasuruan",
  "Payakumbuh",
  "Pekalongan",
  "Pekanbaru",
  "Pematangsiantar",
  "Pontianak",
  "Prabumulih",
  "Probolinggo",
  "Sabang",
  "Salatiga",
  "Samarinda",
  "Sawahlunto",
  "Semarang",
  "Serang",
  "Sibolga",
  "Singkawang",
  "Solok",
  "Sorong",
  "Subulussalam",
  "Sukabumi",
  "Sungai Penuh",
  "Surabaya",
  "Surakarta",
  "Tangerang",
  "Tangerang Selatan",
  "Tarakan",
  "Tasikmalaya",
  "Tebing Tinggi",
  "Tegal",
  "Tanjungbalai",
  "Tanjungpinang",
  "Tual",
  "Tomohon",
  "Yogyakarta"
];
export const COMPANY_TYPES = ["PT", "CV", "Perorangan", "UMKM"];

export const BUSINESS_CATEGORIES = [
  "Fintech", "Edutech", "Healthtech", "Agriculture", "F&B", 
  "Retail", "SaaS", "Logistic", "Creative Agency", "Social Enterprise"
];